export default [
  {
    title: 'Pariwisata Indonesia',
    words: [
      'Masjid Baiturrahman',
      'Pulau Mentawai',
      'Bukittinggi',
      'Jam Gadang',
      'Sungai Musi',
      'Jembatan Ampera',
      'Pulau Lengkuas',
      'Pulau Bintan',
      'Belitung',
      'Danau Kaolin',
      'Bangka',
      'Kelok Sembilan',
      'Danau Singkarak',
      'Danau Toba',
      'Istana Maimun',
      'Pulau Samosir',
      'Teluk Kiluan',
      'Taman Nasional Ujung Kulon',
      'Tanjung Lesung',
      'Pantai Carita',
      'Anyer',
      'Monas',
      'Kepulauan Seribu',
      'Tangkuban Perahu',
      'Kawah Putih',
      'Gedung Sate',
      'Lembang',
      'Pantai Pangandaran',
      'Green Canyon',
      'Keraton Kasepuhan Cirebon',
      'Gua Sunyaragi',
      'Gunung Salak',
      'Gunung Pangrango',
      'Ciwidey',
      'Gunung Sumbing',
      'Puncak',
      'Dataran Tinggi Dieng',
      'Candi Borobudur',
      'Candi Prambanan',
      'Museum Ullen Sentalu',
      'Alun-Alun Yogyakarta',
      'Keraton Yogyakarta',
      'Keraton Solo',
      'Pasar Klewer',
      'Pasar Beringharjo',
      'Jalan Malioboro',
      'Gunung Merbabu',
      'Gunung Merapi',
      'Ketep Pass',
      'Museum Nasional',
      'Museum Kereta Api Ambarawa',
      'Museum Gajah',
      'Galeri Nasional',
      'Pantai Parangtritis',
      'Simpang Lima',
      'Tugu Yogyakarta',
      'Monjali',
      'Kebun Raya Bogor',
      'Istana Bogor',
      'Istana Negara',
      'Lawang Sewu',
      'Sam Poo Kong',
      'Gereja Blenduk',
      'Gereja Ayam Jogja',
      'Taman Sari',
      'Kebun Binatang Ragunan',
      'Benteng Vredeburg',
      'Keraton Mangkunegaran',
      'Taman Mini Indonesia Indah',
      'Keong Mas TMII',
      'Dunia Fantasi Ancol',
      'Masjid Menara Kudus',
      'Masjid Agung Demak',
      'Masjid Istiqlal',
      'Katedral Jakarta',
      'Gunung Bromo',
      'Kawah Ijen',
      'Jembatan Suramadu',
      'Taman Bungkul',
      'Nusa Dua',
      'Pantai Kuta',
      'Seminyak',
      'Ubud',
      'Tanah Lot',
      'Garuda Wisnu Kencana',
      'Dreamland Beach',
      'Canggu',
      'Uluwatu',
      'Gunung Agung',
      'Pantai Senggigi',
      'Pura Besakih',
      'Gunung Batur',
      'Pura Tirta Empul',
      'Gili Trawangan',
      'Gili Lawa',
      'Gunung Rinjani',
      'Danau Segara Anak',
      'Pantai Pink',
      'Desa Sade',
      'Pulau Komodo',
      'Pulau Rinca',
      'Danau Kelimutu',
      'Wae Rebo',
      'Pantai Natsepa',
      'Pulau Kei',
      'Banda Neira',
      'Kepulauan Banda',
      'Kepulauan Tanimbar',
      'Tanjung Puting',
      'Taman Nasional Baluran',
      'Bunaken',
      'Taman Nasional Alas Purwo',
      'G-Land, Banyuwangi',
      'Lembah Baliem',
      'Raja Ampat',
    ],
  },
  {
    title: 'Budaya Indonesia',
    words: [
      'Tari Saman',
      'Tari Ratoh Jaroe',
      'Tari Legong',
      'Tari Kecak',
      'Tari Pendet',
      'Barong',
      'Tari Topeng',
      'Debus',
      'Tari Yapong',
      'Tari Sirih Kuning',
      'Tari Merak',
      'Tari Jaipong',
      'Wayang Golek',
      'Wayang Orang',
      'Wayang Kulit',
      'Wayang Titi',
      'Ronggeng',
      'Tari Serimpi',
      'Tari Bedhaya',
      'Kuda Lumping',
      'Reog Kendang',
      'Reog Ponorogo',
      'Tari Gambyong',
      'Tari Perang',
      'Tari Mandau',
      'Tari Lenso',
      'Tari Jangger',
      'Tari Tandak',
      'Tari Poco-poco',
      'Tari Lilin',
      'Tari Gending Sriwijaya',
      'Tari Tor Tor',
      'Tari Serampang Dua Belas',
      'Topeng Monyet',
      'Srimulat',
      'Ketoprak',
      'Buto Ijo',
      'Malin Kundang',
      'Bawang Merah Bawang Putih',
      'Lutung Kasarung',
      'Jaka Tingkir',
      'Sangkuriang',
      'Roro Jonggrang',
      'Kancil',
      'Cindelaras',
      'Timun Mas',
      'Cepot',
      'Petruk',
      'Gareng',
      'Semar',
      'Bagong',
      'Pandawa Lima',
      'Kurawa',
      'Astina',
      'Mahabharata',
      'Rama Shinta',
      'Hanoman',
      'Anak Kambing Saya',
      'Ayo Mama',
      'Burung Kakatua',
      'Bungong Jeumpa',
      'Cik Cik Periuk',
      'Cublak-cublak Suweng',
      'Desaku',
      'Gelang Sipaku Gelang',
      'Gundhul Pacul',
      'Jali-Jali',
      'Keroncong Kemayoran',
      'Kicir-Kicir',
      'Injit-Injit Semut',
      'Lancang Kuning',
      'Manuk Dadali',
      'Naik-Naik Ke Puncak Gunung',
      'Nona Manis Siapa Yang PUnya',
      'O Ina Ni Keke',
      'Potong Bebek Angsa',
      'Rasa Sayange',
      'Sajojo',
      'Suwe Ora Jamu',
      'Sik Sik Sibatumanikam',
      'Sinanggar Tulo',
      'Timang-Timang Anakku Sayang',
      'Tokecang',
      'Yamko Rambe Yamko',
      'Lompat batu nias',
      'Ulos',
      'Songket',
      'Suntiang',
      'Siger',
      'Paes',
      'Batik Pekalongan',
      'Batik Jogja',
      'Batik Solo',
      'Lurik',
      'Tenun Ikat',
      'Tenun Gedog',
      'Sarung',
      'Batik Tulis',
      'Batik Cap',
      'Songket Sambas',
      'Pakaian Kulit Kayu',
      'Tenun Endek',
      'Tenun Donggala',
      'Tenun Ikat Dayak',
      'Koto Gadang',
      'Solo Basahan',
      'Udeng',
      'Sanggul',
      'Konde',
      'Kebaya',
      'Teluk Belanga',
      'Keris',
      'Centing',
      'Baju Bodo',
      'Phinisi',
      'Ondel-ondel',
      'Roti Buaya',
      'Lenong',
      'Tanjidor',
      'Organ Tunggal',
      'Rebab',
      'Kecapi',
      'Ngaben',
      'Hokkien',
      'Khek',
      'Tionghoa Benteng',
      'Tiochu',
      'Suku Asmat',
      'Suku Dani',
      'Suku Sasak',
      'Dayak',
      'Badui',
      'Minangkabau',
    ],
  },
  {
    title: 'Makanan Indonesia',
    words: [
      'Rendang',
      'Ayam pop',
      'Dendeng balado',
      'Dendeng batokok',
      'Gulai otak',
      'Gulai ayam',
      'Gulai kikil',
      'Kerupuk rambak',
      'Kerupuk karak',
      'Kerupuk puli',
      'Kerupuk kulit',
      'Kerupuk aci',
      'Kerupuk padang',
      'Nasi goreng',
      'Mie goreng',
      'Kwetiau goreng',
      'Mie ayam',
      'Bubur ayam',
      'Nasi uduk',
      'Nasi kuning',
      'Telur dadar',
      'Nasi campur',
      'Tumpeng',
      'Nasi bogana',
      'Gado-gado',
      'Pecel',
      'Karedok',
      'Ketoprak',
      'Asinan Betawi',
      'Asinan Bogor',
      'Pempek',
      'Tekwan',
      'Bakso',
      'Batagor',
      'Siomay',
      'Baso tahu',
      'Lumpia',
      'Serabi',
      'Martabak telur',
      'Martabak manis',
      'Bakwan',
      'Gorengan',
      'Cucur',
      'Kue lumpur',
      'Lemper',
      'Risoles',
      'Pastel',
      'Bakso goreng',
      'Kue lapis',
      'Lapis legit',
      'Kue mangkok',
      'Putu',
      'Apem',
      'Panada',
      'Soto Lamongan',
      'Soto Kudus',
      'Soto ayam',
      'Soto betawi',
      'Soto Madura',
      'Tauto',
      'Sop buntut',
      'Sop kaki kambing',
      'Sop iga',
      'Ayam goreng',
      'Ayam panggang',
      'Ayam betutu',
      'Ayam tangkap',
      'Rolade',
      'Bistik',
      'Ayam penyet',
      'Bebek goreng',
      'Bebek bakar',
      'Ayam goreng mentega',
      'Bebek peking',
      'Sapo tahu',
      'Mapo tahu',
      'Cap cay',
      'Chee Cheong Fan',
      'Coipan',
      'Fuyunghai',
      'Dim sum',
      'Har gow/Hakau',
      'Nasi hainan',
      'Wonton',
      'Suikiaw',
      'Pepes',
      'Lalapan',
      'Sayur nangka',
      'Sayur lodeh',
      'Sayur kangkung',
      'Sayur asem',
      'Iga bakar',
      'Sambal matah',
      'Sambal bawang',
      'Sambal tomat',
      'Sambal luat',
      'Sambal kecap',
      'Sambal terasi',
      'Sambal mangga',
      'Sambal terong',
      'Sambal udang',
      'Opor ayam',
      'Lontong opor',
      'Lontong cap gomeh',
      'Lontong balap',
      'Lontong mie',
      'Sate Madura',
      'Sate kambing',
      'Sate maranggi',
      'Sate lilit',
      'Sate buntel',
    ],
  },
  {
    title: 'Sejarah Indonesia',
    words: [
      'Kutai',
      'Samudera Pasai',
      'Mataram Kuno',
      'Mataram Islam',
      'Majapahit',
      'Sriwijaya',
      'Singosari',
      'Tarumanegara',
      'Pajajaran',
      'Kesultanan Demak',
      'Kerajaan Cirebon',
      'Gowa-Tallo',
      'Ternate dan Tidore',
      'VOC',
      'Daendels',
      'Sir Thomas Stamford Raffles',
      'Douwes Dekker',
      'Multatuli',
      'Max Havelaar',
      'Cournelis de Houtman',
      'Kultuur Stelseel',
      'Pangeran Diponegoro',
      'Jenderal Sudirman',
      'Soekarno',
      'Moch Hatta',
      'Sutan Sjahrir',
      'Sayuti Melik',
      'Bung Tomo',
      'I Gusti Ngurah Rai',
      'Raja Buleleng',
      'Otto Iskandardinata',
      'MH Thamrin',
      'Cut Nyak Dien',
      'RA Kartini',
      'Dewi Sartika',
      'Pattimura',
      'Teuku Umar',
      'Panglima Polim',
      'Tuanku Imam Bonjol',
      'Pangeran Antasari',
      'Sisingamangaraja',
      'Christina Martha Tiahahu',
      'Sultan Hasanuddin',
      'Ki Hajar Dewantara',
      'Tiga Serangkai',
      'Tjipto Mangunkusomo',
      'Budi Utomo',
      'Perang Puputan',
      'Anyer-Panarukan',
      'Sultan Agung',
      'Ageng Tirtayasa',
      'Ken Arok',
      'Ken Dedes',
      'Gajah Mada',
      'Hayam Wuruk',
      'Raden Wijaya',
      'Mpu Tantular',
      'Mpu Gandring',
      'Mpu Prapanca',
      'Nagarakretagama',
      'Raden Patah',
      'Fatahillah',
      'Gunawarman',
      'Mulawarman',
      'Wali Songo',
      'Laksamana Cheng Ho',
      'Sumpah Palapa',
      'Laksamana Maeda',
      'Rengasdengklok',
      'Bandung Lautan Api',
      'Jembatan Merah',
      'Agresi Militer Belanda',
      'Konferensi Meja Bundar',
      'PPKI',
      'BPUPKI',
      'KNIL',
      'Republik Indonesia Serikat',
      'Ade Irma Suryani Nasution',
      'Pierre Tendean',
      'Ahmad Yani',
      'MT Haryono',
      'DI Panjaitan',
      'Trikora',
      'Supersemar',
      'G30S/PKI',
      'Lubang Buaya',
      'Proklamasi',
      'Fatmawati',
      'WR Soepratman',
      'Romusha',
      'Soeharto',
      'BJ Habibie',
      'Megawati Soekarnoputri',
      'Gus Dur',
      'Abdurrahman Wahid',
      'Susilo Bambang Yudhoyono',
      'Joko Widodo',
      'Krismon',
      'Orde Lama',
      'Orde Baru',
      'Reformasi',
      'Kerusuhan Mei 1998',
      'Lingga',
      'Yoni',
      'Prasasti',
      'Kapal Phinisi',
      'Sumpah Pemuda',
      'Jong Java',
      'Sangiran',
      'Dinasti Syailendra',
      'Panembahan Senopati',
      'Kepulauan Banda',
      'Perang Padri',
      'Pithecanthropus erectus',
      'Pancasila',
      'Konferensi Asia Afrika',
      'Dwikora',
      'Pepera - Penentuan Pendapat Rakyat',
      'Tritura - Tri Tuntutan Rakyat',
      'Gerakan Aceh Merdeka',
      'Republik Maluku Selatan',
      'Nadhlatul Ulama',
      'Muhammadiyah',
      'Bom Bali',
      'Tsunami Aceh',
      'Kerusuhan Poso',
      'Timor Timur',
      'Lapindo',
      'Gempa Bantul',
      'Tsunami Mentawai',
    ],
  },
  {
    title: 'Binatang',
    words: [
      'Anjing',
      'Kucing',
      'Cicak',
      'Rayap',
      'Kecoak',
      'Tikus',
      'Nyamuk',
      'Lipan',
      'Tokek',
      'Kelabang',
      'Kaki Seribu',
      'Cacing',
      'Jangkrik',
      'Ulat',
      'Bunglon',
      'Capung',
      'Laron',
      'Kepik',
      'Kumbang',
      'Lintah',
      'Katak',
      'Kodok',
      'Kecebong',
      'Ikan Koi',
      'Ikan Mas',
      'Jerapah',
      'Macan',
      'Macan Tutul',
      'Macan Kumbang',
      'Singa',
      'Ular Piton',
      'Ular Sanca',
      'Ular Kobra',
      'Kuda Nil',
      'Kuda',
      'Kuda Poni',
      'Cheetah',
      'Jaguar',
      'Harimau Sumatera',
      'Rusa',
      'Zebra',
      'Kancil',
      'Anoa',
      'Kerbau',
      'Kambing Gunung',
      'Hyena',
      'Biri-biri',
      'Ayam',
      'Kambing',
      'Domba',
      'Sapi',
      'Babi',
      'Kalkun',
      'Burung Dara',
      'Cendrawasih',
      'Burung Tekukur',
      'Burung Kakatua',
      'Burung Parkit',
      'Burung Jalak',
      'Cucak Rowo',
      'Burung Puter',
      'Jalak Bali',
      'Burung Beo',
      'Merak',
      'Burung Gereja',
      'Elang',
      'Angsa',
      'Bebek',
      'Ayam Hutan',
      'Bangau',
      'Belibis',
      'Burung Betet',
      'Burung Bidadari',
      'Burung Camar',
      'Burung Gagak',
      'Burung Gelatik',
      'Ibis',
      'Itik',
      'Kasuari',
      'Burung Kenari',
      'Maleo',
      'Burung Manyar',
      'Merpati',
      'Rajawali',
      'Babirusa',
      'Babi Hutan',
      'Tapir',
      'Beruang',
      'Beruang Madu',
      'Panda',
      'Beruang Kutub',
      'Serigala',
      'Rottweiler',
      'Golden Retriever',
      'Siberian Husky',
      'Shiba Inu',
      'Akita',
      'Poodle',
      'Chihuahua',
      'Pitbull',
      'Herder',
      'Scottish Fold',
      'Kucing Persia',
      'Kucing Siam',
      'Sphynx Cat',
      'Udang',
      'Lobster',
      'Kepiting',
      'Rajungan',
      'Kerang',
      'Tiram',
      'Siput',
      'Ikan Mas',
      'Ikan Gurame',
      'Mujair',
      'Lele',
      'Tongkol',
      'Tuna',
      'Salmon',
      'Cakalang',
      'Hiu',
      'Paus',
      'Lumba-lumba',
      'Dugong',
      'Bawal',
      'Kakap',
      'Nila',
      'Bandeng',
      'Kacapiring',
      'Selar',
      'Barakuda',
      'Kuda Laut',
      'Kura-kura',
      'Penyu',
      'Gurita',
      'Cumi-cumi',
      'Sotong',
      'Ikan Kembung',
      'Bintang Laut',
      'Ubur-ubur',
      'Landak Laut',
      'Timun Laut',
      'Belut',
      'Ikan Pari',
      'Singa Laut',
      'Anjing Laut',
      'Gajah Laut',
      'Plankton',
      'Gajah',
      'Kangguru',
      'Koala',
      'Wombat',
      'Burung Onta',
      'Tasmanian Devil',
      'Kiwi',
      'Emu',
      'Onta',
      'Burung Nazar',
      'Ular Derik',
      'Kadal Gurun',
      'Iguana',
      'Monyet',
      'Gorila',
      'Kera',
      'Simpanse',
      'Bekantan',
      'Babon',
      'Lutung',
      'Mammoth',
      'Burung Dodo',
    ],
  },
  {
    title: 'Superhero (Campuran)',
    words: [
      'Gundala Putera Petir',
      'Saras 008',
      'Panji Manusia Millenium',
      'Wiro Sableng',
      'Gatotkaca',
      'Si Buta dari Gua Hantu',
      'Si Pitung',
      'Kabayan',
      'Ironman',
      'War Machine',
      'Pepper Potts',
      'Tony Stark',
      'Captain America',
      'Falcon',
      'Steve Rogers',
      'Hulk',
      'Bruce Banner',
      'Valkyrie',
      'Thor',
      'Loki',
      'Odin',
      'Hela',
      'Dr Strange',
      'Stephen Strange',
      'Wong',
      'Ancient One',
      'Dormammu',
      'Spider-man',
      'Peter Parker',
      'Aunt May',
      'Uncle Ben',
      'Gwen Stacy',
      'Mary Jane (Spider-man)',
      'Green Goblin',
      'Doctor Octopus',
      'Hawkeye',
      'Clint Barton',
      'Black Widow',
      'Natasha Romanoff',
      'Black Panther',
      'T’challa',
      'Suri',
      'Captain Marvel',
      'Carol Danvers',
      'Vision',
      'Ant-man',
      'Scott Lang',
      'The Wasp',
      'Guardians of the Galaxy',
      'Rocket',
      'Groot',
      'Gamora',
      'Drax',
      'Starlord/Peter Quill',
      'Daredevil',
      'Bullseye',
      'Elektra',
      'Cerebro',
      'Wolverine',
      'Magneto',
      'Professor X',
      'Charles Xavier',
      'Cyclops',
      'Storm',
      'Phoenix',
      'Rouge',
      'Jean Grey',
      'Mystique',
      'Nightcrawler',
      'Pyro',
      'Angel',
      'Sabertooth',
      'Gambit',
      'Deadpool',
      'Iceman',
      'Beast',
      'Banshee',
      'Colossus',
      'Kitty Pryde/Shadowcat',
      'Jubilee',
      'Psylocke',
      'Quicksilver',
      'Scarlet Witch',
    ],
  },
  {
    title: 'Kartun 2000-an',
    words: [
      'Doraemon',
      'Detektif Conan',
      'Let’s and Go',
      'Crush Gear',
      'Yu-Gi-Oh!',
      'Chibi Maruko Chan',
      'Dragon Ball',
      'Crayon Sinchan',
      'Beyblade',
      'P-man',
      'The Adventures of Honey Bee Hachi',
      'Minky Momo',
      'UFO Baby',
      'Dr Slump',
      'Bubu Chacha',
      'Digimon Adventure',
      'Magical Doremi',
      'Ninja Hatori',
      'Hamtaro',
      'Inuyasha',
      'Samurai X',
      'Captain Tsubasa',
      'Kungfu Boy',
      'Digimon Frontier',
      'Saint Seiya',
      'Nube',
      'Sailormoon',
      'Ninja boy',
      'Kobochan',
      'One Piece',
      'Pokemon',
      'Ge Ge Ge No Kitaro',
      'Bakabon',
      'Cardcaptor Sakura',
      'Mojacko',
      'Mighty Morphin Power Ranger',
      'Zooranger',
      'Tom & Jerry',
      'Looney Tunes',
      'Animania',
      'Rugrats',
      'The Wild Thornberries',
      'Danny Phantom',
      'Jimmy Neutron',
      'The Fairly Oddparents',
      'Totally Spies!',
      'Kim Possible',
      'Avatar: The Legend of Aang',
      'Codename: Kids Next Door',
      'Cat & Dog',
      'Winx',
      'Blue’s Clues',
      'The Powerpuff Girls',
      'Teletubbies',
      'Tweenies',
      'Dora the Explorer',
      'Hey Arnold!',
      'ChalkZone',
    ],
  },
  {
    title: 'Sekitar Rumah',
    words: [
      'Jendela',
      'Pintu',
      'Lantai',
      'Atap',
      'Kasur',
      'Lemari',
      'Meja',
      'Kursi',
      'Kulkas',
      'Dapur',
      'Kompor',
      'Oven',
      'Microwave',
      'Grendel',
      'Knob',
      'Engsel',
      'Steker',
      'Saklar',
      'Kolam',
      'Shower',
      'Heater',
      'Bathtub',
      'Wastafel',
      'Tempat Sampah',
      'Kabel',
      'Meja Rias',
      'Meja Belajar',
      'Karpet',
      'Lukisan',
      'Hangar',
      'Kamper',
      'Credenza',
      'Gorden',
      'Sabun',
      'Shampoo',
      'Pasta gigi',
      'Cukuran',
      'Shower cap',
      'Dental floss',
      'Piyama',
      'Sabun muka',
      'Hair conditioner',
      'Obat kumur',
      'DVD player',
      'Modem',
      'Router',
      'Remote',
      'Sofa',
      'Speaker',
      'Kipas angin',
      'Lampu',
      'AC',
      'Subwoofer',
      'Selimut',
      'Guling',
      'Bantal',
      'Bedcover',
      'Sprei',
      'Pot',
      'Piring',
      'Sendok',
      'Garpu',
      'Pisau',
      'Cangkir',
      'Gelas',
      'Mangkok',
      'Tudung saji',
      'Alas meja',
      'Sendok bebek',
      'Sendok nasi',
      'Mug',
      'Teko',
      'Sumpit',
      'Sedotan',
      'Tusuk gigi',
      'Chandelier',
      'Wajan',
      'Panci',
      'Blender',
      'Coffee maker',
      'Toaster',
      'Garam',
      'Lada',
      'Spatula',
      'Bumbu dapur',
      'Rempah-rempah',
      'Gula',
      'Sirup',
      'Aqua Galon',
      'Fire Extinguisher',
      'Wok',
      'Rice cooker',
      'Talenan',
      'Sabun cuci piring',
      'Panci presto',
      'Cobek',
      'Freezer',
      'Tissue',
      'Lap',
      'Pembersih kaca',
      'Kain pel',
      'Sapu',
      'Sulak',
      'Kemoceng',
      'Equalizer',
      'Pewangi',
      'Selang',
      'Sumur',
      'Sapu lidi',
      'Pengki',
      'Obeng',
      'Tang',
      'Catut',
      'Bor',
      'Kunci',
      'Palu',
      'Paku',
      'Kunci Inggris',
      'Tandon',
      'WC',
      'Bak sampah',
      'Vacuum cleaner',
      'Loteng',
      'Beton',
      'Semen',
      'Kusen',
      'Talang',
      'Plafon',
      'Teralis',
      'Kasa',
    ],
  },
  {
    title: 'Capital Cities of Countries',
    words: [
      'Dhaka',
      'Brussels',
      'Ouagadougou',
      'Sofia',
      'Sarajevo',
      'Bridgetown',
      'Mata Utu',
      'Gustavia',
      'Hamilton',
      'Bandar Seri Begawan',
      'Sucre',
      'Manama',
      'Bujumbura',
      'Porto-Novo',
      'Thimphu',
      'Kingston',
      'Gaborone',
      'Apia',
      'Brasilia',
      'Nassau',
      'Saint Helier',
      'Minsk',
      'Belmopan',
      'Moscow',
      'Kigali',
      'Belgrade',
      'Dili',
      'Saint-Denis',
      'Ashgabat',
      'Dushanbe',
      'Bucharest',
      'Bissau',
      'Hagatna',
      'Guatemala City',
      'Grytviken',
      'Athens',
      'Malabo',
      'Basse-Terre',
      'Tokyo',
      'Georgetown',
      'St Peter Port',
      'Cayenne',
      'Tbilisi',
      "St. George's",
      'London',
      'Libreville',
      'San Salvador',
      'Conakry',
      'Banjul',
      'Nuuk',
      'Gibraltar',
      'Accra',
      'Muscat',
      'Tunis',
      'Amman',
      'Zagreb',
      'Port-au-Prince',
      'Budapest',
      'Hong Kong',
      'Tegucigalpa',
      'Caracas',
      'San Juan',
      'East Jerusalem',
      'Melekeok',
      'Lisbon',
      'Longyearbyen',
      'Asuncion',
      'Baghdad',
      'Panama City',
      'Papeete',
      'Port Moresby',
      'Lima',
      'Islamabad',
      'Manila',
      'Adamstown',
      'Warsaw',
      'Saint-Pierre',
      'Lusaka',
      'El-Aaiun',
      'Tallinn',
      'Cairo',
      'Pretoria',
      'Quito',
      'Rome',
      'Hanoi',
      'Honiara',
      'Addis Ababa',
      'Mogadishu',
      'Harare',
      'Riyadh',
      'Madrid',
      'Asmara',
      'Podgorica',
      'Chisinau',
      'Antananarivo',
      'Marigot',
      'Rabat',
      'Monaco',
      'Tashkent',
      'Nay Pyi Taw',
      'Bamako',
      'Macao',
      'Ulan Bator',
      'Majuro',
      'Skopje',
      'Port Louis',
      'Valletta',
      'Lilongwe',
      'Male',
      'Fort-de-France',
      'Saipan',
      'Plymouth',
      'Nouakchott',
      'Douglas, Isle of Man',
      'Kampala',
      'Dodoma',
      'Kuala Lumpur',
      'Mexico City',
      'Jerusalem',
      'Paris',
      'Diego Garcia',
      'Jamestown',
      'Helsinki',
      'Suva',
      'Stanley',
      'Palikir',
      'Torshavn',
      'Managua',
      'Amsterdam',
      'Oslo',
      'Windhoek',
      'Port Vila',
      'Noumea',
      'Niamey',
      'Kingston',
      'Abuja',
      'Wellington',
      'Kathmandu',
      'Yaren',
      'Alofi',
      'Avarua',
      'Pristina',
      'Yamoussoukro',
      'Berne',
      'Bogota',
      'Beijing',
      'Yaounde',
      'Santiago',
      'West Island',
      'Ottawa',
      'Brazzaville',
      'Bangui',
      'Kinshasa',
      'Prague',
      'Nicosia',
      'Flying Fish Cove',
      'San Jose',
      ' Willemstad',
      'Praia',
      'Havana',
      'Mbabane',
      'Damascus',
      'Philipsburg',
      'Bishkek',
      'Nairobi',
      'Juba',
      'Paramaribo',
      'Tarawa',
      'Phnom Penh',
      'Basseterre',
      'Moroni',
      'Sao Tome',
      'Bratislava',
      'Seoul',
      'Ljubljana',
      'Pyongyang',
      'Kuwait City',
      'Dakar',
      'San Marino',
      'Freetown',
      'Victoria',
      'Astana',
      'George Town',
      'Singapur',
      'Stockholm',
      'Khartoum',
      'Santo Domingo',
      'Roseau',
      'Djibouti',
      'Copenhagen',
      'Road Town',
      'Berlin',
      'Sanaa',
      'Algiers',
      'Washington',
      'Montevideo',
      'Mamoudzou',
      'Beirut',
      'Castries',
      'Vientiane',
      'Funafuti',
      'Taipei',
      'Port of Spain',
      'Ankara',
      'Colombo',
      'Vaduz',
      'Riga',
      "Nuku'alofa",
      'Vilnius',
      'Luxembourg',
      'Monrovia',
      'Maseru',
      'Bangkok',
      'Port-aux-Francais',
      'Lome',
      "N'Djamena",
      'Cockburn Town',
      'Tripolis',
      'Vatican City',
      'Kingstown',
      'Abu Dhabi',
      'Andorra la Vella',
      "St. John's",
      'Kabul',
      'The Valley',
      'Charlotte Amalie',
      'Reykjavik',
      'Tehran',
      'Yerevan',
      'Tirana',
      'Luanda',
      'Pago Pago',
      'Buenos Aires',
      'Canberra',
      'Vienna',
      'Oranjestad',
      'New Delhi',
      'Mariehamn',
      'Baku',
      'Dublin',
      'Jakarta',
      'Kiev',
      'Doha',
      'Maputo',
    ],
  },
  {
    title: 'Countries',
    words: [
      'Bangladesh',
      'Belgium',
      'Burkina Faso',
      'Bulgaria',
      'Bosnia and Herzegovina',
      'Barbados',
      'Wallis and Futuna',
      'Saint Barthelemy',
      'Bermuda',
      'Brunei',
      'Bolivia',
      'Bahrain',
      'Burundi',
      'Benin',
      'Bhutan',
      'Jamaica',
      'Bouvet Island',
      'Botswana',
      'Samoa',
      'Bonaire, Saint Eustatius and Saba ',
      'Brazil',
      'Bahamas',
      'Jersey',
      'Belarus',
      'Belize',
      'Russia',
      'Rwanda',
      'Serbia',
      'East Timor',
      'Reunion',
      'Turkmenistan',
      'Tajikistan',
      'Romania',
      'Tokelau',
      'Guinea-Bissau',
      'Guam',
      'Guatemala',
      'South Georgia and the South Sandwich Islands',
      'Greece',
      'Equatorial Guinea',
      'Guadeloupe',
      'Japan',
      'Guyana',
      'Guernsey',
      'French Guiana',
      'Georgia',
      'Grenada',
      'United Kingdom',
      'Gabon',
      'El Salvador',
      'Guinea',
      'Gambia',
      'Greenland',
      'Gibraltar',
      'Ghana',
      'Oman',
      'Tunisia',
      'Jordan',
      'Croatia',
      'Haiti',
      'Hungary',
      'Hong Kong',
      'Honduras',
      'Heard Island and McDonald Islands',
      'Venezuela',
      'Puerto Rico',
      'Palestinian Territory',
      'Palau',
      'Portugal',
      'Svalbard and Jan Mayen',
      'Paraguay',
      'Iraq',
      'Panama',
      'French Polynesia',
      'Papua New Guinea',
      'Peru',
      'Pakistan',
      'Philippines',
      'Pitcairn',
      'Poland',
      'Saint Pierre and Miquelon',
      'Zambia',
      'Western Sahara',
      'Estonia',
      'Egypt',
      'South Africa',
      'Ecuador',
      'Italy',
      'Vietnam',
      'Solomon Islands',
      'Ethiopia',
      'Somalia',
      'Zimbabwe',
      'Saudi Arabia',
      'Spain',
      'Eritrea',
      'Montenegro',
      'Moldova',
      'Madagascar',
      'Saint Martin',
      'Morocco',
      'Monaco',
      'Uzbekistan',
      'Myanmar',
      'Mali',
      'Macao',
      'Mongolia',
      'Marshall Islands',
      'Macedonia',
      'Mauritius',
      'Malta',
      'Malawi',
      'Maldives',
      'Martinique',
      'Northern Mariana Islands',
      'Montserrat',
      'Mauritania',
      'Isle of Man',
      'Uganda',
      'Tanzania',
      'Malaysia',
      'Mexico',
      'Israel',
      'France',
      'British Indian Ocean Territory',
      'Saint Helena',
      'Finland',
      'Fiji',
      'Falkland Islands',
      'Micronesia',
      'Faroe Islands',
      'Nicaragua',
      'Netherlands',
      'Norway',
      'Namibia',
      'Vanuatu',
      'New Caledonia',
      'Niger',
      'Norfolk Island',
      'Nigeria',
      'New Zealand',
      'Nepal',
      'Nauru',
      'Niue',
      'Cook Islands',
      'Kosovo',
      'Ivory Coast',
      'Switzerland',
      'Colombia',
      'China',
      'Cameroon',
      'Chile',
      'Cocos Islands',
      'Canada',
      'Republic of the Congo',
      'Central African Republic',
      'Democratic Republic of the Congo',
      'Czech Republic',
      'Cyprus',
      'Christmas Island',
      'Costa Rica',
      'Curacao',
      'Cape Verde',
      'Cuba',
      'Swaziland',
      'Syria',
      'Sint Maarten',
      'Kyrgyzstan',
      'Kenya',
      'South Sudan',
      'Suriname',
      'Kiribati',
      'Cambodia',
      'Saint Kitts and Nevis',
      'Comoros',
      'Sao Tome and Principe',
      'Slovakia',
      'South Korea',
      'Slovenia',
      'North Korea',
      'Kuwait',
      'Senegal',
      'San Marino',
      'Sierra Leone',
      'Seychelles',
      'Kazakhstan',
      'Cayman Islands',
      'Singapore',
      'Sweden',
      'Sudan',
      'Dominican Republic',
      'Dominica',
      'Djibouti',
      'Denmark',
      'British Virgin Islands',
      'Germany',
      'Yemen',
      'Algeria',
      'United States',
      'Uruguay',
      'Mayotte',
      'United States Minor Outlying Islands',
      'Lebanon',
      'Saint Lucia',
      'Laos',
      'Tuvalu',
      'Taiwan',
      'Trinidad and Tobago',
      'Turkey',
      'Sri Lanka',
      'Liechtenstein',
      'Latvia',
      'Tonga',
      'Lithuania',
      'Luxembourg',
      'Liberia',
      'Lesotho',
      'Thailand',
      'French Southern Territories',
      'Togo',
      'Chad',
      'Turks and Caicos Islands',
      'Libya',
      'Vatican',
      'Saint Vincent and the Grenadines',
      'United Arab Emirates',
      'Andorra',
      'Antigua and Barbuda',
      'Afghanistan',
      'Anguilla',
      'U.S. Virgin Islands',
      'Iceland',
      'Iran',
      'Armenia',
      'Albania',
      'Angola',
      'Antarctica',
      'American Samoa',
      'Argentina',
      'Australia',
      'Austria',
      'Aruba',
      'India',
      'Aland Islands',
      'Azerbaijan',
      'Ireland',
      'Indonesia',
      'Ukraine',
      'Qatar',
      'Mozambique',
    ],
  },
  {
    title: 'K-Pop',
    words: [
      'BTS',
      'EXO',
      'BIGBANG',
      'Seventeen',
      'BtoB',
      'Red Velvet',
      'AOA',
      "Girls' Generation",
      'SHINee',
      'GOT7',
      'Super Junior',
      '2NE1',
      'Highlight',
      'Infinite',
      '2PM',
      'TWICE',
      'BLACKPINK',
      'Apink',
      'TVXQ',
      'f(x)',
      'B.A.P',
      'CNBLUE',
      'VIXX',
      'B1A4',
      '4Minute',
      'Wonder Girls',
      'Sistar',
      'iKON',
      'Miss A',
      'T-ara',
      'Monsta X',
      'Block B',
      'EXID',
      'GFriend',
      'JYJ',
      'F.T. Island',
      "Girl's Day",
      'KARA',
      'NCT',
      'MBLAQ',
      'MAMAMOO',
      'After School',
      "NU'EST",
      'U-KISS',
      'Teen Top',
      '2AM',
      'WINNER',
      'Wanna One',
      'Brown Eyed Girls',
      'Shinhwa',
      'Astro',
    ],
  },
  {
    title: 'Boso Jowo',
    words: [
      'Mbelgedes',
      'Preketek',
      'Meringis',
      'Merongos',
      'Nyaprut',
      'Mbangir',
      'Mblekenek',
      'Mbledos',
      'Mblenyek',
      'Mlenthung',
      'Ngelemprek',
      'Ngelumbruk',
      'Mbendol',
      'Sangu',
      'Maem',
      'Sikil',
      'Ireng',
      'Abang',
      'Irung',
      'Cangkem',
      'Congor',
      'Idep',
      'Rai',
      'Weteng',
      'Ilat',
      'Ndomble',
      'Njemblung',
      'Ndelower',
      'Mblotrok',
      'Driji',
      'Silit',
      'Kremi',
      'Kelek',
      'Sikut',
      'Murus',
      'Mencret',
      'Ndrodos',
      'Kecirit',
      'Belirik',
      'Melentung',
      'Semok',
      'Mencureng',
      'Lawang',
      'Grendel',
      'Dipan',
      'Bolong',
      'Muprul',
      'Pawon',
      'Kecepit',
      'Sutil',
      'Cowek',
      'Rantang',
      'Gosong',
      'Berambang',
      'Uya',
      'Selindro',
      'Kentir',
      'Wedhok',
      'Banci',
      'Lanang',
      'Nom',
      'Sepuh',
      'Arek',
      'Wong',
      'Mbok',
      'Uti',
      'Akung',
      'Mbah',
      'Jotak',
      'Bangkekan',
      'Asu',
      'Ulo',
      'Wedhus',
      'Undur-undur',
      'Luwing',
      'Tekek',
      'Iwak',
      'Londo',
      'Jaran',
      'Kebo',
      'Nyambik',
      'Gantrung',
      'Budhe',
      'Pakde',
      'Pak lik',
      'Bu lik',
      'Jarik',
      'Bojo',
      'Garwo',
      'Putu',
      'Buyut',
      'Geringgingen',
      'Gatelen',
      'Biduren',
      'Kukulen',
      'Cantengen',
      'Beleken',
      'Curek',
      'Mencureng',
      'Kopok',
      'Wawik',
      'Adus',
      'Luwe',
      'Wareg',
      'Nesu',
      'Isuk',
      'Sesuk',
      'Awan',
      'Bengi',
      'Sore',
      'Manjing',
      'Surup',
      'Wingi',
      'Mben',
      'Ngarep',
      'Mburi',
      'Iringan',
      'Ngiwo',
      'Nganan',
      'Nduwur',
      'Nisor',
      'Nyungsep',
      'Ndelengsep',
      'Tibo',
      'Blendrang',
      'Karak',
      'Nyambel',
      'Menyet',
    ],
  },
  {
    title: 'Lagu 2000-an',
    words: ['(BAM) Betapa Aku Mencintaimu (Vagetoz)', '11 Januari (Gigi)', 'Ada Apa Dengan Cinta (feat. Eric) (Melly Goeslaw, Eric)', 'Ada Apa Denganmu (Peterpan)', 'Akhir Cerita Cinta (Glenn Fredly)', 'Akhirnya Ku Menemukanmu (NaFF)', 'Aku & Bintang (Peterpan)', 'Aku Bertahan (Rio Febrian)', 'Aku Bukan Pilihan (Iwan Fals)', 'Aku Bukan Pilihan Hatimu (Ungu)', 'Aku Bukan Untukmu (Rossa)', 'Aku Cinta Dia (Gita Gutawa)', 'Aku Cinta Kau Dan Dia (The Rock)', 'Aku Dan Dirimu (feat. Bunga Citra Lestari) (Ari Lasso, Bunga Citra Lestari)', 'Aku Harus Jujur (Kerispatih)', 'Aku Pasti Kembali (Pasto)', 'Akulah Dia (Drive)', 'Antara Ada Dan Tiada (Utopia)', 'Arti Sahabat (Nidji)', 'Atas Nama Cinta (Rossa)', 'Bahasa Kalbu (Titi DJ)', 'Baik Baik Sayang (Wali)', 'Bawalah Cintaku (Afgan)', 'BBC - Benci Bilang Cinta (Radja)', 'Be Mine (Aditya)', 'Begitu Salah Begitu Benar (Dewi - Dewi)', 'Bendera (Cokelat)', 'Berdua Lebih Baik (Acha Septriasa)', 'Berharap Tak Berpisah (Reza Artamevia)', 'Berhenti Berharap (Sheila On 7)', 'Berita Kepada Kawan (Ebiet G. Ade)', 'Bernafas Tanpamu (Lyla)', 'Bersama Bintang (Drive)', 'Bertahan (Five Minutes)', 'Biarlah (Nidji)', 'Bila Aku Jatuh Cinta (Nidji)', 'Bila Rasaku Ini Rasamu (Kerispatih)', 'Bimbang (Melly Goeslaw)', 'Bintang Di Surga (Peterpan)', 'Buka Hatimu (Armada)', 'Bukan Diriku (SAMSONS)', 'Bukan Superstar (Project Pop)', 'Bukan Untukku (Rio Febrian)', 'Bukannya Aku Takut (Juliette)', 'Bulan (Radja)', 'Cari Jodoh (Wali)', 'Cari Pacar Lagi (ST12)', 'Ceria (J-Rocks)', 'Cinderella (Radja)', 'Cinta (Chrisye)', 'Cinta (Vina Panduwinata)', 'Cinta Begini (Tangga)', 'Cinta Dalam Hati (Ungu)', 'Cinta Dan Rahasia (Yura Yunita, Glenn Fredly)', 'Cinta Di Ujung Jalan (Agnes Monica)', "Cinta Ini Membunuhku (D'MASIV)", 'Cinta Pertama (Sunny) (Bunga Citra Lestari)', 'Cinta Pertama Dan Terakhir (Sherina)', 'Cinta Sampai Disini (D\'MASIV)', "Cinta Sampai Disini (D'MASIV)", 'Cinta Tak Bersyarat (Element)', 'Cinta Tak Mungkin Berhenti (Tangga)', 'Cinta Terakhir (Ari Lasso)', 'Cintailah Aku Sepenuh Hati (Ari Lasso)', 'Cintakan Membawamu Kembali (Reza Artamevia)', 'Cintaku (Chrisye)', 'Cobalah Mengerti (Peterpan)', 'Dan... (Sheila On 7)', 'Dealova (Once Mekel)', 'Demi Cinta (Kerispatih)', 'Demi Waktu (Ungu)', 'Denting (Melly Goeslaw)', 'Dewi (Dewa 19)', "Dia (MALIQ & D'Essentials)", 'Dia Milikku (Yovie & Nuno)', 'Diam Tanpa Kata (D\u00e2\u20ac\u2122MASIV)', 'Diantara Kalian (D\u00e2\u20ac\u2122MASIV)', 'Diatas Normal (Peterpan)', 'Dibalas Dengan Dusta (Audy)', 'Dibalik Awan (Peterpan)', 'Disco Lazy Time (Nidji)', 'Doo Be Doo (Gita Gutawa)', 'Doy (Kangen Band)', 'Elang (Dewa 19)', 'Firasat (Marcell)', 'Gantung (Melly Goeslaw)', 'Goyang Duyu (Project Pop)', 'Hampa (Ari Lasso)', 'Hanya Ingin Kau Tahu (Repvblik)', 'Hanya Kamu Yang Bisa (Tiket)', 'Hapus Aku (Nidji)', 'Haruskah Kumati (Ada Band)', 'Hebat (Tangga)', 'Hidupku Kan Damaikan Hatimu (Caffeine)', 'Hijrah Ke London (The Changcuters)', 'Hingga Akhir Waktu (NINEBALL)', 'I Heart You (SMASH)', 'I Love U Bibeh (The Changcuters)', 'I Miss U But I Hate U (Slank)', 'I Will Fly (Ten2Five)', 'Ijinkan Aku Menyayangimu (Iwan Fals)', 'Itu Aku (Sheila On 7)', 'Jadi Gila (RAN)', 'Jadikan Aku Yang Kedua (Astrid)', 'Jagoan (Sherina, Rodo)', 'Jangan Kau Lepas (Alexa)', 'Jangan Lupakan (Nidji)', 'Jangan Pernah Berubah (Marcell)', 'Jangan Pernah Berubah (ST12)', 'Janji Suci (Yovie & Nuno)', 'Januari (Glenn Fredly)', 'Jenuh (Rio Febrian)', 'Jika (feat. Ari Lasso) (Melly Goeslaw, Ari Lasso)', 'Jomblo (Saykoji)', 'JPP - Jangan Pernah Pergi (Alexa)', 'Jujur (Radja)', 'Kamu Yang Pertama (Geisha)', 'Kamulah Satu Satunya (Dewa 19)', 'Kangen (Dewa 19)', 'Karena Ku Sanggup (Agnes Monica)', 'Karena Wanita - Ingin Dimengerti (Ada Band)', 'Karma (Cokelat)', 'Kasih Putih (Glenn Fredly)', 'Kasih Tak Sampai (Padi)', 'Kau Cantik Hari Ini (Lobow)', 'Kau Dan Aku (Nidji)', 'Kau Masih Kekasihku (NaFF)', 'Kecewa (Bunga Citra Lestari)', 'Kejujuran Hati (Kerispatih)', 'Kekasih Gelapku (Ungu)', 'Kekasih Sejati (Monita)', 'Kemenangan Hati (Dirly & Ghea)', 'Kenangan Terindah (SAMSONS)', 'Kesempatan Kedua (Tangga)', 'Kesepian (Dygta)', 'Kesepian Kita (feat. Tere) (Pas Band, Tere)', 'Ketahuan (Matta)', 'Kisah Cintaku (Peterpan)', 'Kisah Kasih di Sekolah (Chrisye)', 'Kisah Tak Sempurna (SAMSONS)', 'Kisah Yang Salah (Glenn Fredly)', 'KKEB (Andre Hehanussa)', 'Ku Tak Bisa (Slank)', 'Kucinta Kau Apa Adanya (Once Mekel)', 'Kukatakan Dengan Indah (Peterpan)', 'Kupu Kupu Malam (Peterpan)', 'Lagu Rindu (Kerispatih)', 'Larut (Dewa 19)', 'Lelaki Buaya Darat (Ratu)', 'Lirih (Ari Lasso)', 'Luluh (SAMSONS)', 'Maafkan (Rio Febrian)', 'Mahadewi (Padi)', 'Main Hati (Andra And The Backbone)', 'Mantan Kekasih (Lyla)', 'Manusia Bodoh (Ada Band)', 'Masih - Sahabatku Kekasihku (Ada Band)', 'Masih Ada (Ello)', 'Masih Cinta (Kotak)', 'Matahariku (Agnes Monica)', 'Melepasmu (Drive)', 'Melompat Lebih Tinggi (Sheila On 7)', 'Menangis Semalam (Audy)', 'Menanti Sebuah Jawaban (Padi)', 'Mengejar Matahari (Ari Lasso)', 'Mengenangmu (Kerispatih)', 'Menghapus Jejakmu (Peterpan)', 'Menghitung Hari 2 (Anda)', 'Menghujam Jantungku (Tompi)', 'Menjaga Hati (Yovie & Nuno)', 'Menunggumu (Feat. Chrisye) (Peterpan)', 'Menunggumu feat Peterpan (Chrisye)', 'Merindukanmu (D\u00e2\u20ac\u2122MASIV)', "Merindukanmu (D'MASIV)", 'Mimpi Yang Sempurna (Peterpan)', 'Munajat Cinta (The Rock)', 'Mungkin Nanti (Peterpan)', 'Musnah (Andra And The Backbone)', 'My Heart (Acha Septriasa, Irwansyah)', 'Nuansa Bening (Vidi Aldiano)', 'P.U.S.P.A. (ST12)', 'Pandangan Pertama (RAN)', 'Parasit (Gita Gutawa)', 'Pelan Pelan Saja (Kotak)', 'Pelangi Di Matamu (Jamrud)', 'Pencinta Wanita (Irwansyah)', 'Pergi Untuk Kembali (Ello)', 'Pergilah Kasih (Chrisye)', 'Pergilah Kau (Sherina)', 'Perih (Vierra)', 'Permintaan Hati (Letto)', 'Pernah Muda (Bunga Citra Lestari)', "Pilihanku (MALIQ & D'Essentials)", 'Pudar (Rossa)', 'Puisi (Jikustik)', 'Pupus (Dewa)', 'Putus Nyambung (BBB)', 'Racun Dunia (The Changcuters)', 'Rahasia Hati (Element)', 'Rahasia Perempuan (Ari Lasso)', 'Rapuh (Agnes Monica)', 'Rasa Ini (Vierra)', 'Rasa Yang Tertinggal (ST12)', 'Rindu (Agnes Monica)', 'Risalah Hati (Dewa)', 'Roman Picisan (Dewa 19)', 'Ruang Rindu (Letto)', 'Saat Bahagia (Ungu, Andien)', 'Saat Terakhir (ST12)', 'Sampai Menutup Mata (Acha Septriasa)', 'Sampai Nanti, Sampai Mati (Letto)', 'Sandaran hati (Letto)', 'Sebelum Cahaya (Letto)', 'Seberapa Pantas (Sheila On 7)', 'Sebuah Kisah Klasik (Sheila On 7)', 'Sedang Ingin Bercinta (Dewa 19)', 'Sedari Dulu (Tompi)', 'Sedih Tak Berujung (Glenn Fredly)', 'Sejauh Mungkin (Ungu)', 'Sekali Ini Saja (Glenn Fredly)', "Selamanya Cinta (D'Cinnamons)", 'Semakin Ku Kejar Semakin Kau Jauh - Sksj (Five Minutes)', 'Sempat Memiliki (Yovie & Nuno)', 'Sempurna (Andra And The Backbone)', 'Semua Tak Sama (Padi)', 'Semusim (Marcell)', 'Sepanjang Hidupku (Pilot)', 'Separuh Jiwaku Pergi (Anang)', 'Separuh Nafas (Dewa 19)', 'Seperti Yang Dulu (Ungu)', 'Seperti Yang Kau Minta (Chrisye)', 'Sephia (Sheila On 7)', 'Setengah Hati (Ada Band)', 'Setia (Jikustik)', 'Slalu Mengalah (Seventeen)', 'Soulmate (Kahitna)', 'Status Palsu (Vidi Aldiano)', 'Suara (Ku Berharap) (Hijau Daun)', 'Suara Hati Seorang Kekasih (Melly Goeslaw)', 'Sudah (Nidji)', 'Surga Cinta (Ada Band)', 'Tak Ada Logika (Agnes Monica)', 'Tak Ada Yang Bisa (Andra And The Backbone)', 'Tak Bisakah (Peterpan)', 'Tak Kan Pernah Ada (Geisha)', 'Tak Lekang Oleh Waktu (Kerispatih)', 'Tak Pernah Setengah Hati (Tompi)', 'Tak Seindah Cinta Yang Semestinya (NaFF)', 'Tanpa Cinta (Yovie & Nuno)', 'Tapi Bukan Aku (Kerispatih)', 'Tegar (Rossa)', 'Tentang Aku,Kau dan Dia (Kangen Band)', 'Tentang Seseorang (Anda Perdana)', 'Terbaik Untukmu (Tangga)', 'Terbaik Untukmu (TIC Band)', 'Terbang (Gigi)', 'Tercipta Untukku (Ungu)', 'Terendap Laraku (NaFF)', 'Terima Kasih Cinta (Afgan)', 'Terpesona (Glenn Fredly, Audy)', 'Terserah (Glenn Fredly)', 'Tetes Embun (Glenn Fredly)', 'Topeng (Peterpan)', 'Tulus (Radja)', "Untitled (MALIQ & D'Essentials)", 'Walau Habis Terang (Peterpan)', 'When You Love Someone (Endah N Rhesa)', 'Ya Sudahlah (Bondan Prakoso, Fade2Black)', 'Yang Terbaik Bagimu - Jangan Lupakan Ayah (Ada Band)', 'Yang Terdalam (Peterpan)'],
  },
  {
    title: 'Film & Serial Indonesia',
    words: ['Laskar Pelangi', 'Habibie & Ainun', 'Ayat-Ayat Cinta', 'Ketika Cinta Bertasbih', '5 CM', 'The Raid', 'Sang Pemimpi', 'Tenggelamnya Kapal Van Der Wijck', 'Comic 8', 'The Raid 2', 'Get Married', 'Surga Yang Tak Dirindukan', 'Garuda Di Dadaku', 'Nagabonar Jadi 2', 'Sang Pencerah', 'Terowongan Casablanca', '99 Cahaya di Langit Eropa', 'Tali Pocong Perawan', 'Air Terjun Pengantin', 'Quickie Express', 'Soekarno: Indonesia Merdkea', 'The Tarix Jabrix', 'Cinta Brontosaurus', 'Suster Keramas', 'Suster Ngesot The Movie', 'Perempuan Berkalung Sorban', 'Negeri 5 Menara', 'Surat Kecil Untuk Tuhan', 'Arwah Goyang Karawang', 'Otomatis Romantis', 'Merry Riana : Mimpi Sejuta Dolar', 'Kutunggu Jandamu', 'Setan Budeg', 'Hafalan Shalat Delisa', 'Cinlok', 'Pulau Hantu', 'Purple Love', 'Merah Putih', 'Marmut Merah Jambu', 'Perahu Kertas', 'Soegija', 'Ada Apa Dengan Cinta', 'Dilan 1990', 'Dilan 1991', 'Pengabdi Setan', 'Warkop DKI Reborn', 'Suzanna', 'Bajaj Bajuri the Movie', 'Milea: Suara dari Dilan', 'My Stupid Boss', 'Cek Toko Sebelah', "Eiffel I'm In Love", 'Jailangkung', 'Dua Garis Biru', 'Nanti Kita Cerita tentang Hari Ini', 'Perempuan Tanah Jahanam', 'Keluarga Cemara', 'Gundala', '#TemanTapiMenikah', 'Milly & Mamet', 'Wiro Sableng: Pendekar Kapak Maut Naga Geni 212', 'A Man Called Ahok', 'Bumi Manusia', 'Kuntilanak', 'Surat Cinta Untuk Starla', 'Akhir Kisah Cinta Si Doel', 'Preman Pensiun', 'Sebelum Iblis Menjemput', 'Orang Kaya Baru', 'Legenda Putri Duyung', 'Di Sini Ada Setan', 'Inikah Rasanya', 'Si Cecep', 'Buku Harian Nayla', 'Heart', 'Kepompong', 'Buku Harian Baim', 'Pernikahan Dini', 'Kisah Sedih di Hari Minggu', 'Bidadari', 'Tersanjung', 'Extravaganza', 'Opera van Java', 'Bawang Merah Bawang Putih', 'Lupus Milenia', 'Siapa Takut Jatuh Cinta', 'Saras 008', 'Cinta Fitri', 'Angling Dharma', 'Akademi Fantasi Indosiar', 'Cahaya', 'Who Wants to be a Millionaire', 'Si Doel', 'Dunia Lain', 'Katakan Cinta', 'Audisi Pelawak TPI', 'Spontan Uhuy', 'Termehek-Mehek', 'On The Spot', 'Dahsyat', 'Sketsa', 'Magic', 'The Master', 'Uang Kaget', 'Bedah Rumah', 'Karma', 'Katakan Putus', 'Rumah Uya', 'Lorong Waktu', 'Kiamat Sudah Dekat', 'Sahur Kita', 'Silet', 'Cek & Ricek', 'Kick Andy', 'Si Unyil', 'Tetangga Masa Gitu', 'Mata Najwa', 'Kisah Kasih Di Sekolah', 'Gerhana', 'Benci Bilang Cinta', 'Ganteng-Ganteng Serigala', 'MasterChef', 'Putri yang Ditukar', 'Tukang Bubur Naik Haji', 'Tukang Ojek Pengkolan', 'Galileo', 'Komunikata', 'Kata Berkait', 'Apa Ini Apa Itu', 'Tak Tik Boom', 'Siapa Berani?', 'Famili 100', 'Kena Deh', 'Jin dan Jun', 'Tuyul dan Mbak Yul', 'Benteng Takeshi', 'Indonesian Idol'],
  },
  {
    title: 'Musisi Indonesia',
    words: ['/rif', '3 Diva', '5Romeo', 'AB Three', 'Abdul & The Coffee Theory', 'Acha Septriasa', 'Ada Band', 'Adera', 'Adhitia Sofyan', 'Afgan', 'Agnes Monica', 'Alexa', 'Amigdala', 'Anang', 'Andien', 'Andra and the Backbone', 'Andre Hehanusa', 'Anggun', 'Angkasa', 'Anji', 'Ari Lasso', 'Armada', 'Astrid', 'Audy', 'Ballads of the Clich\u00e9', 'Banda Neira', 'Barasuara', 'Base Jam', 'Beat Burger', 'Bening', 'Bondan Prakoso', 'Bukan Bintang Biasa (BBB)', 'Bunga Citra Lestari', 'Chrisye', 'Cinta Laura Kiehl', 'Clubeighties', 'Cokelat', 'Danilla', "D'Bagindas", "D'Cinnamons", 'Debu', 'Derby', 'Dewa', 'Dewa 19', 'Dewi Dewi', 'Dewi Lestari', 'Dewi Sandra', "D'Masiv", 'Drive', 'Dygta', 'Ebiet G Ade', 'Ecoutez!', 'Efek Rumah Kaca', 'Element', 'Ello', 'Emerald', 'Endah n Rhesa', 'Endank Soekamti', 'Evo', 'Five Minutes', 'Float', 'Fourtwnty', 'Funky Kopral', 'Garasi', 'Geisha', 'Gigi', 'Gita Gutawa', 'Glenn Fredly', 'Goliath', 'GRUVI', 'Hello', 'Hijau Daun', 'Homogenic (HMGNC)', 'Iwa K', 'Iwan Fals', 'Jamrud', 'Java Jive', 'Jikustik', 'J-Rocks', 'Juliette', 'Kahitna', 'Kangen Band', 'Katon Bagaskara', 'Kerispatih', 'Kla Project', 'Kotak', 'Krakatau', 'Krisdayanti', 'Kuburan', 'Letto', 'Lobow', 'Lyla', 'Mahadewi', 'Maia', "Malis & D'essentials", 'Marcell', 'MarcoMarche', 'Matta', 'Maudy Ayunda', 'Melly Goeslaw', 'Memes', 'Mocca', 'Monita', 'Mulan Jameela', 'Naff', 'Naif', 'Netral', 'Nicky Astria', 'Nidji', 'Noah', 'Nosstress', 'Nugie', 'Numata', 'Once Mekel', 'Padi', 'PAS Band', 'Pasto', 'Payung Teduh', 'Peterpan', 'Petra Sihombing', 'Pilot', 'Pinkan Mambo', 'Porotonema', 'Potret', 'Project Pop', 'Pusakata', 'Radja', 'Raisa', 'RAN', 'Ratu', 'Repvblik', 'Reza Artamevia', 'Rio Febrian', 'Rossa', 'Ruth Sahanaya', 'Samsons', 'Sandhy Sondoro', 'Saykoji', 'Senar Senja', 'Seventeen', 'Shanty', 'She', 'Sheila Majid', 'Sheila on 7', 'Sherina', 'Silampukau', 'sind3ntosca', 'Sisitipsi', 'Siti Nurhaliza', 'Slank', 'SMASH', 'Sore', 'Soulvibe', 'ST12', 'Steven & Coconut Treez', 'Stinky', 'Superman Is Dead', 'T.R.I.A.D.', 'T2', 'Tangga', 'Ten2Five', 'Tengkorak', 'Tere', 'The Adams', 'The Changcuters', 'The Groove', 'The Rock', 'The Upstairs', 'Titi DJ', 'Tompi', 'Tulus', 'Ungu', 'Ussy', 'Utopia', 'Vagetoz', 'Vidi Aldiano', 'Vierra', 'Vina Panduwinata', 'Wali', 'Warna', 'White Shoes & The Couples Company', 'Yovie & Nuno', 'Zigaz'],
  },
  {
    title: 'Movies 2000s',
    words: ['3 Idiots', 'A Beautiful Mind', 'Am\u00e9lie', 'Batman Begins', 'Black Swan', 'City of God', 'District 9', 'Donnie Darko', 'Eternal Sunshine of the Spotless Mind', 'Finding Nemo', 'Gladiator', 'Gran Torino', 'Hotel Rwanda', 'How to Train Your Dragon', "Howl's Moving Castle", 'Inception', 'Inglourious Basterds', 'Into the Wild', 'Ip Man', 'Kill Bill: Vol. 1', 'Million Dollar Baby', 'Monsters, Inc.', 'No Country for Old Men', "Pan's Labyrinth", 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Ratatouille', 'Shutter Island', 'Sin City', 'Slumdog Millionaire', 'Spirited Away', 'Star Trek', 'The Bourne Ultimatum', 'The Dark Knight', 'The Departed', "The King's Speech", 'The Lord of the Rings: The Fellowship of the Ring', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'The Pianist', 'The Prestige', 'There Will Be Blood', 'Toy Story 3', 'Up', 'V for Vendetta', 'WALL\u00b7E', 'Moulin Rouge!', 'The Devil Wears Prada', 'The Sisterhood of the Traveling Pants', 'The Hangover', 'Requiem for a Dream', 'Oldboy', 'The Royal Tenenbaums', 'Tropic Thunder', "Bridget Jones's Diary", "Harry Potter and the Sorcerer's Stone", 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Order of Phoenix', 'Harry Potter and the Half-Blood Prince', 'Barbershop', "Ocean's Eleven", "Ocean's Twelve", "Ocean's Thirteen", 'Avatar', 'Paranormal Activity', 'Walk The Line', 'In Bruges', 'Mean Girls', 'Erin Brockovich', '500 Days of Summer', 'The 40-Year-Old-Virgin', 'Inside Man', '28 Days Later', 'Superbad', 'Brokeback Mountain', 'Shrek', 'Shrek 2', 'In The Mood For Love', 'Coraline', 'Shaolin Soccer', 'Zodiac', 'Borat', 'Little Miss Sunshine', 'School of Rock', 'Hot Fuzz', 'Minority Report', 'Shaun of the Dead', 'Children of Men', 'Spider-Man 2', 'Spider-Man', 'Spider-Man 3', 'Iron Man', 'Spy Kids', 'Casino Royale', 'Juno', 'Before Sunset', 'Chicken Run', 'The Incredibles', 'The Hurt Locker', 'Crouching Tiger, Hidden Dragon', 'Confession of a Teenage Drama Queen', 'The Princess Diaries', 'The Perfect Score', '17 Again', 'A Cinderella Story', "She's the Man", 'Easy A', 'Napoleon Dynamite', 'Bring It On', 'High School Musical', 'Bend It Like Beckham', 'Freaky Friday', 'The Wedding Planner', 'How to Lose a Guy in 10 Days', 'Knocked Up', 'The Notebook', 'A Walk to Remember', 'Legally Blonde', 'The Proposal', 'Dreamgirls', '13 Going on 30', 'Miss Congeniality', 'Love Actually', 'The Holiday', 'Mamma Mia!', 'The Princess and the Frog', 'The Lizzie McGuire Movie', 'The Polar Express', 'The Family Stone', 'Ice Age: Dawn of the Dinosaurs', 'Shrek the Third', 'Ice Age: The Meltdown', 'Kung Fu Panda', 'Madagascar: Escape 2 Africa', 'Madagascar', 'Cars', 'Shrek', 'Happy Feet', 'Ice Age', 'Monsters vs. Aliens', 'Bee Movie', 'Lilo & Stitch', 'Brother Bear', 'Cloudy with a Chance of Meatballs', 'Ponyo', 'Atlantis: The Lost Empire', 'Meet the Robinsons', "The Emperor's New Groove", 'Monster Houes', 'The SpongeBob SquarePants Movie', "Pirates of the Caribbean: Dead Man's Chest", "Pirates of the Caribbean: At World's End", 'Star Wars: Episode III - Revenge of the Sith', 'Transformers: Revenge of the Fallen', 'Indiana Jones and the Kingdom of Crystal Skull', 'The Da Vinci Code', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'The Matrix Reloaded', '2012', 'Transformers', 'The Twilight Saga: New Moon', 'Star Wars: Episode II - Attack of the Clones', 'Hancock', 'War of the Worlds', 'Quantum of Solace', 'I am Legend', 'Night at the Museum', 'Mission: Impossible 2', 'Saw', 'Save the Last Dance', 'Twilight', 'The Fast and the Furious', 'Taken', 'Mr & Mrs Smith', '300', 'Zoolander', 'American Psycho', "Something's Gotta Give", 'The Ring', 'Remember the Titans', 'V for Vendetta', 'Black Hawk Down', 'Cloverfield', 'Elf', 'Anchorman - The Legend of Ron Burgundy', 'Fahrenheit 9/11', 'Mulholland Drive', 'Billy Elliot', 'X2: X-Men United', 'Collateral', 'Ghost World', 'Broken Flowers', 'Almost Famous', '4 Months, 3 Weeks, and 2 Days', 'The Wrestler', 'Lost in Translation'],
  },
  {
    title: "Music of the '00s",
    words: ['Paramore', 'My Chemical Romance', 'Panic! At The Disco', 'Evanescence', 'Jimmy Eat World', 'Taking Back Sunday', 'The Used', 'Fall Out Boy', 'Finch', 'Good Charlotte', 'Blink 182', 'Thursday', 'AFI', 'Say Anything', 'Boys Like Girls', 'Dashboard Congessional', 'Coheed and Cambria', 'Circa Survive', 'Cute Is What We Aim For', 'The Red Jumpsuit Apparatus', 'Story of The Year', 'Yellowcard', 'Hawthorne Heights', 'All Time Low', 'Motion City Soundtrack', 'Anberlin', 'Silverstein', 'The All-American Rejects', 'The Fall of Troy', 'Aiden', 'The Rocket Summer', 'Sum 41', 'Hoobastank', 'Simple Plan', 'Thirty Seconds To Mars', 'Angels & Airwaves', 'Bowling For Soup', 'Breaking Benjamin', '3 Doors Down', 'We The Kings', 'Linkin Park', 'Green Day', 'A Day To Remember', 'The Wanted', 'The Click Five', 'Incubus', 'Red Hot Chili Peppers', 'The Calling', 'Switchfoot', 'System Of A Down', 'The Killers', "Plain White T's", 'Rise Against', 'Forever The Sickest Kids', 'The Goo Goo Dolls', 'Avril Lavigne', 'Mayday Parade', 'Papa Roach', 'Muse', 'Matchbox Twenty', 'Arctic Monkeys', 'Jason Mraz', 'Mandy Moore', 'Westlife', 'The Pussycat Dolls', 'James Blunt', 'S Club 7', 'Alicia Keys', 'Michael Buble', 'Five For Fighting', 'Coldplay', 'Backstreet Boys', 'Miley Cyrus', 'Daniel Bedingfield', 'Natasha Bedingfield', 'John Mayer', 'Taylor Swift', 'Daniel Powter', "Destiny's Child", 'Kelly Clarkson', 'Gwen Stefani', 'John Legend', 'India Arie', 'Mariah Carey', 'Jennifer Lopez', 'Usher', 'Britney Spears', 'Bon Jovi', '*NSYNC', 'Eminem', 'Robbie Williams', 'Christina Aguilera', 'Janet Jackson', 'Missy Elliott', 'Oasis', 'R. Kelly', 'Kylie Minogue', 'Jay-Z', 'P!nk', 'Madonna', 'Enrique Iglesias', 'All Saints', 'The Corrs', 'Ronan Keating', 'Aaliyah', 'Ricky Martin', 'Santana', 'U2', 'Creed', 'Radiohead', 'Lifehouse', 'Limp Bizkit', 'Marilyn Manson', 'Deftones', 'Rage Against The Machine', 'The Offspring', 'Disturbed', 'The Wombats', 'Fountains of Wayne', 'Jet', 'Franz Ferdinand', 'Jonas Brothers', 'Cobra Starship', 'Gym Class Heroes', 'Kings of Leon', 'Kings of Convenience', '3OH!3', 'Katy Perry', 'The Kooks', 'Michelle Branch', 'Counting Crows', 'Maroon 5', 'Nickelback', 'Daughtry', 'Gorillaz', 'The White Stripes', 'Smash Mouth', 'The Fray', 'Owl City', 'Jesse McCartney', 'Foo Fighters', 'OK Go', 'The Temper Trap', 'Two Door Cinema Club', 'Secondhand Serenade', 'Train', 'Weezer', 'Amy Winehouse', 'Death Cab for Cutie', 'Fergie', 'Black Eyed Peas', 'Justin Timberlake', 'Lindsay Lohan', 'Daft Punk', 'Carrie Underwood', 'One Republic', 'Ludacris', '+44', 'The Strokes', 'MIKA', 'Fatboy Slim', 'Ne-Yo', 'Kelly Rowland', 'Ciara', 'Chris Brown', 'Lil Wayne', 'Akon', 'Pitbull', 'T-Pain', 'Snoop Dogg', 'Timbaland', 'Beyonce', 'Leona Lewis', 'Rihanna', '50 Cent', 'Outkast', 'Blur', 'Placebo', 'The Clash', 'The Cure', 'Kasabian', 'The Stone Roses', 'Snow Patrol', 'New Order', 'Adele', 'Natalie Imbruglia'],
  },
];
